apiVersion: apps/v1
kind: Deployment
metadata:
  annotations:
    kompose.cmd: kompose convert -f compose.yml
    kompose.version: 1.22.0 (955b78124)
  creationTimestamp: null
  labels:
    io.kompose.service: payment-service-container
  name: payment-service-container
spec:
  replicas: 1
  selector:
    matchLabels:
      io.kompose.service: payment-service-container
  strategy: {}
  template:
    metadata:
      annotations:
        kompose.cmd: kompose convert -f compose.yml
        kompose.version: 1.22.0 (955b78124)
      creationTimestamp: null
      labels:
        io.kompose.network/microservices_network: "true"
        io.kompose.service: payment-service-container
    spec:
      containers:
        - env:
            - name: EUREKA_CLIENT_AVAILABILITYZONES_DEFAULT
              value: myzone
            - name: EUREKA_CLIENT_REGION
              value: default
            - name: EUREKA_CLIENT_SERVICEURL_DEFAULTZONE
              value: http://service-discovery-container:8761/eureka/
            - name: EUREKA_CLIENT_SERVICEURL_MYZONE
              value: http://service-discovery-container:8761/eureka
            - name: SPRING_CONFIG_IMPORT
              value: optional:configserver:http://cloud-config-container:9296/
            - name: SPRING_PROFILES_ACTIVE
              value: dev
            - name: SPRING_ZIPKIN_BASE-URL
              value: http://zipkin:9411
            - name : EUREKA_INSTANCE_HOSTNAME
              value: payment-service-container
            - name: EUREKA_INSTANCE_PREFER_IP_ADDRESS
              value: "false"
          image: selimhorri/payment-service-ecommerce-boot:0.1.0
          name: payment-service-container
          ports:
            - containerPort: 8400
          resources: {}
      restartPolicy: Always
status: {}
