name: Auto PR from stage to master

on:
  push:
    branches:
      - stage

jobs:
  create-pull-request:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout repository
        uses: actions/checkout@v4

      - name: Create Pull Request to master
        uses: peter-evans/create-pull-request@v6
        with:
          token: ${{ secrets.GITHUB_TOKEN }}
          base: master
          branch: stage
          title: 'Sync stage to master'
          body: |
            Se generó automáticamente un Pull Request para propagar los últimos cambios de `develop` a `master`.
          draft: false
