name: Auto Merge stage into master

on:
  push:
    branches:
      - stage

permissions:
  contents: write
  pull-requests: write

jobs:
  auto-merge:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v4
        with:
          fetch-depth: 0 

      - name: Create and merge PR
        uses: devops-infra/action-pull-request@v0.5.1
        with:
          github_token: ${{ secrets.GITHUB_TOKEN }}
          source_branch: stage
          target_branch: master
          title: Auto merge stage to master
          body: Auto merge generado por CI
          draft: false
          allow_no_diff: true 
