name: Auto PR from develop to stage

on:
  push:
    branches:
      - develop

jobs:
  create-pull-request:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout repository
        uses: actions/checkout@v4

      - name: Create Pull Request to stage
        uses: peter-evans/create-pull-request@v6
        with:
          token: ${{ secrets.GITHUB_TOKEN }}
          base: stage
          branch: develop
          title: 'Sync develop to stage'
          body: |
            Se generó automáticamente un Pull Request para propagar los últimos cambios de `develop` a `stage`.
          draft: false
