name: Auto Merge develop into stage

on:
  push:
    branches:
      - develop

permissions:
  contents: write
  pull-requests: write

jobs:
  auto-merge:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Create and merge PR
        uses: devops-infra/action-pull-request@v0.5.1
        with:
          github_token: ${{ secrets.GITHUB_TOKEN }}
          source_branch: develop
          target_branch: stage
          title: Auto merge develop to stage
          body: Auto merge generado por CI
          reviewers: sebas3004tian
          assignees: sebas3004tian
          delete_source_branch: false
          merge_method: merge
