name: Develop CI/CD for favourite-service only on relevant changes

on:
  push:
    branches:
      - develop
    paths:
      - 'favourite-service/**'

jobs:
  build_and_push:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout repository
        uses: actions/checkout@v4

      - name: Validate DockerHub secrets
        run: |
          if [ -z "${{ secrets.DOCKER_USERNAME }}" ] || [ -z "${{ secrets.DOCKER_PASSWORD }}" ]; then
            echo "DockerHub credentials are not set!" >&2
            exit 1
          fi

      - name: Set up JDK 11
        uses: actions/setup-java@v4
        with:
          java-version: '11'
          distribution: 'adopt'

      - name: Build with Maven (skip tests)
        run: mvn -B package -DskipTests --file pom.xml

      - name: Docker Login
        run: echo "${{ secrets.DOCKER_PASSWORD }}" | docker login -u "${{ secrets.DOCKER_USERNAME }}" --password-stdin

      - name: Build Docker image for favourite-service
        run: |
          IMAGE_TAG=develop-${{ github.run_number }}
          docker build -f favourite-service/Dockerfile \
            -t ${{ secrets.DOCKER_USERNAME }}/favourite-service-ecommerce-boot:$IMAGE_TAG .

      - name: Push Docker image
        run: |
          IMAGE_TAG=develop-${{ github.run_number }}
          docker push ${{ secrets.DOCKER_USERNAME }}/favourite-service-ecommerce-boot:$IMAGE_TAG
