name: Notify Develop

on:
  pull_request:
    branches:
      - develop
    types: [opened, closed]

jobs:
  notify-develop:
    runs-on: ubuntu-latest
    steps:
      - name: Extract PR data
        id: pr_data
        uses: actions/github-script@v7
        with:
          script: |
            const pr = context.payload.pull_request;
            const merged = pr.merged;
            const data = {
              title: pr.title,
              author: pr.user.login,
              body: pr.body,
              url: pr.html_url,
              base_branch: pr.base.ref,   // <- rama destino (por ejemplo: develop)
              head_branch: pr.head.ref,   // <- rama origen (por ejemplo: feature/login)
              merged_by: merged ? pr.merged_by.login : null
            };
            core.setOutput("data", JSON.stringify(data));

      - name: Notify Slack
        if: github.event.pull_request.merged == true
        uses: slackapi/slack-github-action@v1.25.0
        with:
          payload: |
            {
              "text": ":rocket: *Merge to Develop!* PR by ${{ steps.pr_data.outputs.data }}"
            }
        env:
          SLACK_WEBHOOK_URL: ${{ secrets.SLACK_WEBHOOK }}

      - name: Send email notification
        if: github.event.pull_request.merged == true
        uses: dawidd6/action-send-mail@v3
        with:
          server_address: smtp.your-email.com
          server_port: 587
          username: ${{ secrets.EMAIL_USERNAME }}
          password: ${{ secrets.EMAIL_PASSWORD }}
          subject: "[Dev PR] ${{ github.event.pull_request.title }}"
          to: team@yourcompany.com
          body: |
            Pull Request Details:
            Title: ${{ github.event.pull_request.title }}
            Author: ${{ github.event.pull_request.user.login }}
            Merged By: ${{ github.event.pull_request.merged_by.login }}
            URL: ${{ github.event.pull_request.html_url }}

      - name: Notify Admins
        if: github.event.pull_request.merged == true
        run: |
          echo "Sending detailed report to admins..."
          # Aquí puedes usar otra llamada a Slack o email más detallada.
